### ISSUE TITLE
Git tags

### ISSUE THREAD

**Issue by AltNico** [jklmnn/ParkenDD#29]
In order for F-Droid to detect updates, you need to tag your releases. The last version on F-Droid is 0.8.1 which is also your last Git tag.

Could you please tag the latest stable version?

**Comment by jklmnn** [comment]
0.8.1 is currently the latest stable release. I'm working together with the guys from https://github.com/offenesdresden/ParkAPI .  
Since the API is currently not stable I don't want to publish a version that suddenly might not work anymore.  
I will definitely draft a new release, I just can't give you a date, but I hope that it will be in September.

**Comment by AltNico** [comment]
@jklmnn OK, thank you for your reply.
I think, I can close this.
